name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install Python dependencies
      if: steps.setup-python.outputs.cache-hit != 'true'
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run CI checks
      run: |
        chmod +x ci.sh
        ./ci.sh
